CREATE DATABASE  IF NOT EXISTS basedatos_02;
USE basedatos_02;

DROP TABLE IF EXISTS coche;
CREATE TABLE coche (
  MATRICULA	varchar(7) NOT NULL,
  MARCA			varchar(10) NOT NULL,
  AÑOS				int NOT NULL,
  PROVINCIA	varchar(10) NOT NULL,
  PRIMARY KEY (MATRICULA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES coche WRITE;
INSERT INTO coche VALUES ('1111ABC','BMW',4,'ALBACETE'),('2222CDM','MERCEDES',12,'MADRID'),('3333POK','FIAT',2,'CUENCA');
UNLOCK TABLES;